from shipcheck.engine import run_audit


def test_bad_fixture_flags_payment_risks():
    report = run_audit("tests/fixtures/next_supabase_bad")
    ids = {f.id for f in report.findings}
    assert "payments.webhook_no_signature" in ids
    assert "payments.success_grants_entitlement" in ids


def test_clean_fixture_avoids_signature_finding():
    report = run_audit("tests/fixtures/next_supabase_clean")
    assert not any(f.id == "payments.webhook_no_signature" for f in report.findings)


def test_tutorial_folder_named_webhooks_does_not_make_every_file_webhook(tmp_path):
    folder = tmp_path / "21-subscribe-to-stripe-webhooks-using-next-js-api-routes" / "pages" / "api"
    folder.mkdir(parents=True)
    (folder / "create-stripe-customer.js").write_text(
        """
        import Stripe from "stripe";
        export default async function handler(req, res) {
          const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
          const customer = await stripe.customers.create({ email: "a@example.com" });
          res.json(customer);
        }
        """,
        encoding="utf-8",
    )
    report = run_audit(str(tmp_path))
    assert not any(f.id == "payments.webhook_no_signature" for f in report.findings)


def test_unverified_stripe_webhook_still_gets_signature_finding(tmp_path):
    route = tmp_path / "app" / "api" / "stripe" / "webhook"
    route.mkdir(parents=True)
    (route / "route.ts").write_text(
        """
        import Stripe from "stripe";
        export async function POST(req: Request) {
          const event = await req.json();
          if (event.type === "checkout.session.completed") return Response.json({ ok: true });
          return Response.json({ received: true });
        }
        """,
        encoding="utf-8",
    )
    report = run_audit(str(tmp_path))
    assert any(f.id == "payments.webhook_no_signature" for f in report.findings)


def test_verified_stripe_webhook_avoids_signature_finding(tmp_path):
    route = tmp_path / "app" / "api" / "stripe" / "webhook"
    route.mkdir(parents=True)
    (route / "route.ts").write_text(
        """
        import Stripe from "stripe";
        export async function POST(req: Request) {
          const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!);
          const signature = req.headers.get("stripe-signature")!;
          const event = stripe.webhooks.constructEvent(await req.text(), signature, process.env.STRIPE_WEBHOOK_SECRET!);
          return Response.json({ received: true });
        }
        """,
        encoding="utf-8",
    )
    report = run_audit(str(tmp_path))
    assert not any(f.id == "payments.webhook_no_signature" for f in report.findings)


def test_generated_file_with_price_id_does_not_get_hardcoded_price(tmp_path):
    generated = tmp_path / "supabase" / "types_db.ts"
    generated.parent.mkdir(parents=True)
    generated.write_text(
        """
        // This file was generated by Supabase.
        export type Database = { price_id: "price_1234567890abcdef" };
        """,
        encoding="utf-8",
    )
    report = run_audit(str(tmp_path))
    assert not any(f.id == "payments.hardcoded_price" for f in report.findings)
