from __future__ import annotations

from pathlib import Path
import re

from shipcheck.models import AuditContext, Finding, SourceFile

SERVER_HINTS = ("app/api/", "pages/api/", "middleware", "server", "route.ts", "route.js")
CLIENT_HINTS = ("app/", "pages/", "components/", "lib/", "src/")
CODE_SUFFIXES = (".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".py")


def norm_path(path: str) -> str:
    return path.replace("\\", "/").lower()


def redact(value: str | None) -> str | None:
    if not value:
        return value
    text = value.strip().replace("'", "").replace('"', "")
    for token in re.findall(r"(sk_(?:live|test)_[A-Za-z0-9]{8,}|sk-[A-Za-z0-9_-]{12,}|eyJ[A-Za-z0-9_.-]{20,})", text):
        text = text.replace(token, token[:8] + "...REDACTED")
    for token in re.findall(r"=([A-Za-z0-9_./+-]{16,})", text):
        text = text.replace(token, token[:4] + "...REDACTED")
    return text[:160]


def finding(id_: str, category: str, severity: str, title: str, source: SourceFile | None = None, line: int | None = None, evidence: str | None = None, why: str = "", fix: str = "") -> Finding:
    return Finding(id=id_, category=category, severity=severity, title=title, file=source.rel_path if source else None, line=line, evidence=redact(evidence), why_it_matters=why, remediation=fix)


def line_has(text: str, *needles: str) -> bool:
    low = text.lower()
    return any(n.lower() in low for n in needles)


def is_client_path(path: str) -> bool:
    low = norm_path(path)
    return any(h in low for h in CLIENT_HINTS) and not any(h in low for h in ("app/api/", "pages/api/", "server/"))


def is_route_file(path: str) -> bool:
    low = norm_path(path)
    name = Path(low).name
    return low.startswith("app/api/") and name in {"route.ts", "route.tsx", "route.js", "route.jsx", "route.mjs", "route.cjs"}


def is_api_route(path: str) -> bool:
    low = norm_path(path)
    return is_route_file(low) or (low.startswith("pages/api/") and low.endswith(CODE_SUFFIXES))


def is_generated_file(path: str, text: str = "") -> bool:
    low_path = norm_path(path)
    low_text = text.lower()
    name = Path(low_path).name
    generated_names = {
        "types_db.ts",
        "database.types.ts",
        "supabase.types.ts",
        "schema.types.ts",
    }
    return (
        name in generated_names
        or ".generated." in low_path
        or "database.types" in low_path
        or "supabase.types" in low_path
        or "types_db" in low_path
        or ("supabase" in low_path and name in {"types.ts", "types_db.ts"})
        or "this file was generated" in low_text
        or "generated by" in low_text
        or ("export type json" in low_text and "database" in low_text)
    )


def is_server_only_path(path: str, text: str = "") -> bool:
    low = norm_path(path)
    low_text = text.lower()
    return (
        low.startswith("app/api/")
        or low.startswith("pages/api/")
        or "/server/" in low
        or low.startswith("server/")
        or "/lib/server/" in low
        or "/libs/server/" in low
        or "server-only" in low_text
        or "supabase-admin" in low
        or "admin-client" in low
    )


def is_likely_client_reachable(path: str, text: str = "") -> bool:
    low = norm_path(path)
    low_text = text.lower()
    if is_server_only_path(low, text):
        return False
    if '"use client"' in low_text or "'use client'" in low_text:
        return True
    if low.startswith("components/") or "/components/" in low:
        return True
    if low.startswith("pages/") and not low.startswith("pages/api/"):
        return True
    return False


def verifies_stripe_signature(text: str) -> bool:
    return line_has(text, "constructEvent", "stripe-signature", "STRIPE_WEBHOOK_SECRET", "stripe_webhook_secret")


def is_stripe_webhook_route(source: SourceFile) -> bool:
    if not is_api_route(source.rel_path):
        return False
    low_path = norm_path(source.rel_path)
    low_text = source.text.lower()
    has_stripe_context = "stripe" in low_path or "stripe" in low_text
    has_webhook_context = "webhook" in Path(low_path).parts or "webhook" in Path(low_path).name or "webhook" in low_text
    has_event_context = line_has(
        source.text,
        "constructEvent",
        "stripe-signature",
        "checkout.session.completed",
        "customer.subscription",
        "invoice.paid",
        "invoice.payment",
        "payment_intent",
    )
    return has_stripe_context and (has_webhook_context or has_event_context) and has_event_context


def is_jsx_placeholder_attribute(line: str) -> bool:
    low = line.lower()
    return bool(re.search(r"\bplaceholder\s*=", low))


def is_tailwind_placeholder_class(line: str) -> bool:
    return bool(re.search(r"\bplaceholder:[a-z0-9_/\-[\]:.]+", line.lower()))


def has_file(ctx: AuditContext, *names: str) -> bool:
    wanted = set(names)
    return any(Path(f.rel_path).name in wanted or f.rel_path in wanted for f in ctx.files)


def code_files(ctx: AuditContext) -> list[SourceFile]:
    return ctx.by_suffix(*CODE_SUFFIXES)
